[env:esp32dev]
platform  = espressif32 @ ^6.0.0
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags = -O3

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
